### ISSUE TITLE
Problem running example

### ISSUE THREAD

**Issue by jvitkovsky** [midraed/water#17]
Just trying to get the "simple" example code to work.  The issue is with running:

WeatherStation <- read.WSdata(WSdata = csvfile, date.format = "%d/%m/%Y",
 lat=-35.42222, long= -71.38639, elev=201, height= 2.2,
 MTL = MTLfile)

I receive the error:

Error in Ops.data.frame(WS.after, WS.prev) : 
  ‘-’ only defined for equally-sized data frames

I am using the latest R version 3.2.4 and RStudio.

Kind regards,

John

**Comment by midraed** [comment]
Sorry, but I can't reproduce your error. Can you try running these lines:

    library(water)
    csvfile <- system.file("extdata", "apples.csv", package="water")
    MTLfile <- system.file("extdata", "L7.MTL.txt", package="water")
    WeatherStation <- read.WSdata(WSdata = csvfile, date.format = "%d/%m/%Y",
                  lat=-35.42222, long= -71.38639, elev=201, height= 2.2,
                  MTL = MTLfile)

And tell me if you have the same error...!

csvfile should point to a file like this:

    > csvfile
    [1] "/home/guillermo/R/x86_64-pc-linux-gnu-library/3.2/water/extdata/apples.csv"

kind regards

**Comment by jvitkovsky** [comment]
Hi Guillermo,

Thanks for the reply.  Here is a log of what I get when I run those lines:


> library(water)
Loading required package: raster
Loading required package: rgdal
rgdal: version: 1.1-3, (SVN revision 594)
Geospatial Data Abstraction Library extensions to R successfully loaded
Loaded GDAL runtime: GDAL 2.0.1, released 2015/09/15
Path to GDAL shared files: C:/Users/vitkovskyj/Documents/R/win-library/3.2/rgdal/gdal
GDAL does not use iconv for recoding strings.
Loaded PROJ.4 runtime: Rel. 4.9.1, 04 March 2015, [PJ_VERSION: 491]
Path to PROJ.4 shared files: C:/Users/vitkovskyj/Documents/R/win-library/3.2/rgdal/proj
Linking to sp version: 1.2-2
> csvfile <- system.file("extdata", "apples.csv", package="water")
> MTLfile <- system.file("extdata", "L7.MTL.txt", package="water")
> WeatherStation <- read.WSdata(WSdata = csvfile, date.format = "%d/%m/%Y",
+                               lat=-35.42222, long= -71.38639, elev=201, height= 2.2,
+                               MTL = MTLfile)
Error in Ops.data.frame(WS.after, WS.prev) :
  ‘-’ only defined for equally-sized data frames
>
> print(csvfile)
[1] "C:/Users/vitkovskyj/Documents/R/win-library/3.2/water/extdata/apples.csv"
> print(MTLfile)
[1] "C:/Users/vitkovskyj/Documents/R/win-library/3.2/water/extdata/L7.MTL.txt"



I checked the path to the files and it seems ok.  I’m really not quite sure what’s going on.

Kind regards,

JV

**Comment by midraed** [comment]
It looks like a problem related to regional configuration. Thank you for helping to track the bug.

Can you try this:
```
WeatherStation <- read.WSdata(WSdata = csvfile, date.format = "%d/%m/%Y",
              lat=-35.42222, long= -71.38639, elev=201, height= 2.2)
```

**Comment by midraed** [comment]
JV, I think the problem it's related to the MTL file.

Can you try this:

```
MTLfile <- system.file("extdata", "L7.MTL.txt", package="water")
MTL <- readLines(MTLfile, warn=FALSE)
    time.line <- grep("SCENE_CENTER_TIME",MTL,value=TRUE)
    date.line <- grep("DATE_ACQUIRED",MTL,value=TRUE)
    sat.time <-regmatches(time.line,regexec(text=time.line,
           pattern="([0-9]{2})(:)([0-9]{2})(:)([0-9]{2})(.)([0-9]{2})"))[[1]][1]
    sat.date <-regmatches(date.line,regexec(text=date.line,
                        pattern="([0-9]{4})(-)([0-9]{2})(-)([0-9]{2})"))[[1]][1]
    sat.datetime <- strptime(paste(sat.date, sat.time), 
                             format = "%Y-%m-%d %H:%M:%S", tz="GMT")
sat.date
sat.datetime
```

**Comment by jvitkovsky** [comment]
Hi Guillermo,

Sorry, but I've been busy.  I get this:

`> library(water)
> aoi <- createAoi(topleft = c(273110, -3914450),
+ bottomright = c( 288050, -3926650), EPSG = 32619)
> csvfile <- system.file("extdata", "apples.csv", package="water")
> MTLfile <- system.file("extdata", "L7.MTL.txt", package="water")
> MTL <- readLines(MTLfile, warn=FALSE)
> time.line <- grep("SCENE_CENTER_TIME",MTL,value=TRUE)
> date.line <- grep("DATE_ACQUIRED",MTL,value=TRUE)
> sat.time <-regmatches(time.line,regexec(text=time.line,
+ pattern="([0-9]{2})(:)([0-9]{2})(:)([0-9]{2})(.)([0-9]{2})"))[[1]][1]
> sat.date <-regmatches(date.line,regexec(text=date.line,
+ pattern="([0-9]{4})(-)([0-9]{2})(-)([0-9]{2})"))[[1]][1]
> sat.datetime <- strptime(paste(sat.date, sat.time),
+ format = "%Y-%m-%d %H:%M:%S", tz="GMT")
> sat.date
[1] "2013-02-15"
> sat.datetime
[1] "2013-02-15 14:30:40 GMT"`

**Comment by irlandahernandez** [comment]
Yo tenía el mismo error 
Lo solucioné
Los datos de mi estación meteorológica tenían una fecha diferente a la fecha de la imagen. 
Cuando tuvieron la misma fecha, desapareció el error.
