### ISSUE TITLE
Error object 'image_TOA' not found

### ISSUE THREAD

**Issue by suryakant54321** [midraed/water#25]
While using raw Landsat 8 data I am getting following error.
Error in names(imagestack) <- stack.names : object 'image_TOA' not found.
I am using water version 0.5.

**Comment by suryakant54321** [comment]
The snippet for TOA conversion is not available for Landsat 8 (ref: water_RSfunctions.R).

**Comment by midraed** [comment]
Exactly. You should download the surface reflectance image from ESPA.usgs.gov!
