### ISSUE TITLE
Error in read.WSdata()

### ISSUE THREAD

**Issue by rokoeh** [midraed/water#30]
Hello

I'm having a issue while reading some weather station data:

csvfile<-"E:/estatistica/projetos/metric/estacoes/ea614.csv"
MTLfile<-"E:/estatistica/projetos/metric/imagens/landsat/LC08_L1TP_216073_20160531_20170324_01_T1/LC08_L1TP_216073_20160531_20170324_01_T1_MTL.txt"

read.WSdata(WSdata =csvfile, height=2, lat=-19.356923 ,long=-40.068680 , elev=38, tz="UTC", date.format = "%Y-%m-%d", time.format = "%h",MTL = MTLfile, columns=c("date","time", "radiation", "wind", NA, "RH", "temp", "pp"))

Error in data.frame(date = unique(WSdata$date), radiation_sum = tapply(WSdata$radiation,  : 
  arguments imply differing number of rows: 1, 0

There is any mistake?

Here is the used data:

https://drive.google.com/open?id=0B3f-4ojGAWWXVnZBbDRVMmlNd2s

Nevermind... The error ocurred because the time format was wrong (%h in place of %H) and the data was with a extra column in front of it from when I used the command write.csv()

It is recommended to create a new error message when the result of this code is all NA:
 datetime <- strptime(datetime, format = datetime.format, 
                           tz = tz)

It is recommended to change the way the correct data columns order is informed. It is a little confusing.

Sorry for bothering. Thanks

**Comment by midraed** [comment]
Your last suggestion is the same as #29 
Thank you very much! I did the changes proposed.

Regards!
