### ISSUE TITLE
Error in dailyET()

### ISSUE THREAD

**Issue by rokoeh** [midraed/water#34]
When using the function:

dailyET(Wtst, lat=-18.78062 ,long=-40.98651 , elev=255, ET="ETr")

The function returns NA. 

Here is the waterWeatherStation object: https://drive.google.com/open?id=0B3f-4ojGAWWXT2NiQWpxcWY1c3M

This may be fixed by changing the last line of the function: return(sum(ET.daily)) by return(sum(ET.daily, na.rm=T))

Thanks

**Comment by midraed** [comment]
Fixed. Thank you @rokoeh

**Comment by ishwar97** [comment]
@midraed The error does not seemed to be fixed in water version 0.8. Please verify the same.
Thanks

**Comment by midraed** [comment]
It's fixed on the current version and the development version. Can you install the development version following the instruction on the readme.md here?

**Comment by ishwar97** [comment]
Thank you so much! Its been fixed in new version!
