### ISSUE TITLE
Ts datum v//s TsDEM

### ISSUE THREAD

**Issue by IFuentesSR** [midraed/water#36]
Hi,
I'm trying to implement the metric model on another language and I have realized that when estimating the sensible heat the model uses the following algorithm:
Ts.datum <- Ts - (DEM - WeatherStation$elev) * 6.49 / 1000
However, in the literature most authors describe this variable as TsDEM, which has a small difference compared to your implementation:
TsDEM = Ts + 0.0065Δz,
where Δz is the elevation of each pixel minus the elevation of a datum (meters), and corresponds to the term (DEM - WeatherStation$elev) of your equation. However, in the original equation this is added to the surface temperature, but in your algorithm it's subtracted.
Can you please confirm if this was intended to work that way or if it's just a mistake.
Regards

**Comment by midraed** [comment]
Fixed! Thank you @IFuentesSR , @magosilvain
